### ISSUE TITLE
Typo in CompanySettings.OrganisationNumber still persist in NuGet version 3.3.5 despite the fix being included in release details.

### ISSUE THREAD

**Issue by erik-bizzdo** [FortnoxAB/csharp-api-sdk#107]
We suffer problem of not getting an organization number while fetching company settings and we have been relying on a workaround to get the OrgNo from the VAT number instead.

We happily upgraded from 3.3.4 to 3.3.5 to get the fix (commit [d81ebd4](https://github.com/FortnoxAB/csharp-api-sdk/commit/d81ebd47f9f4ce4f589cfe2bba1e755e92f3c4b0))
The source code for the release contains the fix, but the NuGet doesn't.
Visual Studio still show the property as OrganisationNumber on the class FortnoxAPILibrary.Entities.CompanySettings.

**Comment by richardrandak** [comment]
Sorry for the trouble. I'll check it and fix the NuGet

**Comment by richardrandak** [comment]
I could not update existing NuGet, so I published 3.3.6 instead. 
Thank you and please let me know in case of any other issues.

**Comment by erik-bizzdo** [comment]
Thank you for the quick resolve. Version 3.3.6 did solve our problem.

Från: richardrandak <notifications@github.com>
Skickat: den 29 september 2020 14:35
Till: FortnoxAB/csharp-api-sdk <csharp-api-sdk@noreply.github.com>
Kopia: Erik Rydgren <erik@bizzdo.se>; Author <author@noreply.github.com>
Ämne: Re: [FortnoxAB/csharp-api-sdk] Typo in CompanySettings.OrganisationNumber still persist in NuGet version 3.3.5 despite the fix being included in release details. (#107)


I could not update existing NuGet, so I published 3.3.6 instead.
Thank you and please let me know in case of any other issues.
